name: ParkingE2E
channels:
    - conda-forge
    - pytorch
    - nvidia
    - defaults
dependencies:
    - cryptography=38.0.2=py37h38fbfac_1
    - cuda-cudart=11.7.99=0
    - cuda-cupti=11.7.101=0
    - cuda-libraries=11.7.1=0
    - cuda-nvrtc=11.7.99=0
    - cuda-nvtx=11.7.91=0
    - cuda-runtime=11.7.1=0
    - empy=3.3.4=pyh9f0ad1d_1
    - gnutls=3.7.9=hb077bed_0
    - numpy=1.21.5=py37h6c91a56_3
    - numpy-base=1.21.5=py37ha15fc14_3
    - pillow=9.4.0=py37h6a678d5_0
    - pip=22.3.1=py37h06a4308_0
    - python=3.7.16=h7a1cb2a_0
    - pytorch=1.13.1=py3.7_cuda11.7_cudnn8.5.0_0
    - pytorch-cuda=11.7=h778d358_5
    - pytorch-mutex=1.0=cuda
    - setuptools=65.6.3=py37h06a4308_0
    - torchaudio=0.13.1=py37_cu117
    - torchvision=0.14.1=py37_cu117
    - typing_extensions=4.3.0=py37h06a4308_0
    - urllib3=1.26.14=py37h06a4308_0
    - wheel=0.38.4=py37h06a4308_0
    - pip:
          - click==8.1.7
          - efficientnet-pytorch==0.7.1
          - gnupg
          - loguru==0.7.0
          - opencv-python==4.8.0.76
          - pycryptodomex
          - pyquaternion==0.9.9
          - pytorch-lightning==1.5.0
          - pyyaml==6.0.1
          - tensorboard==2.11.2
          - tensorboard-data-server==0.6.1
          - tensorboard-plugin-wit==1.8.1
          - timm==0.9.7
          - tqdm==4.66.1
          - shapely==2.0.5
          - scipy==1.7.3
          - rospkg==1.5.0